services:
  serve:
    build: ./docs
    command: serve -a 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    working_dir: /project
  mike-serve:
    build: ./docs
    entrypoint: mike
    command: serve -a 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    working_dir: /project
  mike-deploy-latest:
    build: ./docs
    entrypoint: mike
    command: deploy latest
    volumes:
      - .:/project
    working_dir: /project