site_name: HaCraFu Bausätze
site_url: https://hacrafu.github.io/assembly-kits/
site_dir: 'docbuild/kits'

theme:
  name: material
  language: de
  logo: 'assets/images/hacrafu.svg'
  features:
    - navigation.expand
    - navigation.sections
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

plugins:
  - search:                                         
      lang: de
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: de
          default: true
          name: Deutsch
          build: true
          site_name: "HaCraFu Bausätze"
          nav_translations:
            Kits: Bausätze
        - locale: en
          name: English
          build: true
          site_name: "HaCraFu assembly kits"

extra:
  alternate:
    - name: Deutsch
      link: ""
      lang: de
    - name: English
      link: en
      lang: en
  homepage: https://hacrafu.de
  version:
    provider: mike
    default: latest

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

edit_uri: edit/main/docs

repo_url: https://github.com/hacrafu/assembly-kits