M48
; DRILL file {KiCad 7.0.2.1-36-g582732918d-dirty-deb11} date Fri Jan 19 22:57:27 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-19T22:57:27+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2.1-36-g582732918d-dirty-deb11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X0.0Y-8.0
T0
M30
